defaults:
  - env_config: target-N4C4S3S1
  - _self_

wandb:
  mode: online
  project: STORM-OCRL
  entity: null
  name: null
  group: target
  tags: null
  notes: null

initialization:
  resume_ckpt: null
  pretrained_ckpt: null

common:
  max_steps: 102000
  seed: 0
  image_size: 64
  device: cuda:0
  resume: False
  load_pretrained: False

envs:
  env_type: ocrl
  env_name: target-N4C4S3S1
  num_envs: 1
  max_step: 50
  config: ${env_config}

replay_buffer:
  _target_: replay_buffer.OCRLReplayBuffer
  max_episodes: 10000
  max_length: 50
  warmup_length: 1024
  store_on_gpu: True

training:
  batch_size: 32
  demonstration_batch_size: 0
  batch_length: 16
  imagine_batch_size: 1024
  imagine_demonstration_batch_size: 0
  imagine_context_length: 4
  imagine_batch_length: 20
  train_dynamics_every_steps: 1
  train_agent_every_steps: 1
  use_demonstration: False
  trajectory_path: null
  #############################
  save_every_steps: 2500
  vis_every_steps: 1000
  inspect_every_steps: 1000
  inspect_batch_size: 16
  inspect_context_length: 8
  inspect_batch_length: 16

evaluation:
  max_step: 2048
  num_episodes: 100

world_model:
  _target_: sub_models.world_models.WorldModel
  lr: 0.0001
  max_grad_norm: 1000.0
  in_channels: 3
  stem_channels: 32
  stoch_num_classes: 32
  stoch_dim: 32
  transformer_max_length: 64
  transformer_hidden_dim: 512
  transformer_num_layers: 2
  transformer_num_heads: 8
  agent_state_type: both

agent:
  _target_: agents.ActorCriticAgent
  num_layers: 2
  hidden_dim: 512
  gamma: 0.985
  lambd: 0.95
  entropy_coef: 3.0e-4
  lr: 3.0e-5
  max_grad_norm: 100.0