defaults:
  - env_config: target-N4C4S3S1
  - _self_

wandb:
  mode: online
  project: STORM-OCRL
  entity: null
  name: null
  group: token_vis2
  tags: null
  notes: null

initialization:
  resume_ckpt: null

common:
  num_epochs: 5
  seed: 0
  image_size: 64
  device: cuda:0
  resume: False

training:
  batch_size: 24
  demonstration_batch_size: 0
  batch_length: 1
  train_dynamics_every_steps: 1
  use_demonstration: False
  trajectory_path: null
  #############################
  save_every_steps: 2500
  vis_every_steps: 1000
  inspect_every_steps: 1000

world_model:
  _target_: sub_models.slate.SLATE
  lr_vae: 0.0003
  lr_sa: 0.0001
  lr_dec: 0.0003
  max_grad_norm_vae: 0.05 # or 1
  max_grad_norm_sa: 0.05 # or 1
  max_grad_norm_dec: 0.05 # or 1
  in_channels: 3
  stem_channels: 64
  stoch_num_classes: 256
  stoch_dim: 192
  num_slots: 7
  slot_dim: 192
  dec_hidden_dim: 512
  dec_num_layers: 2
  vocab_size: 4096
  post_type: mlp
  loss_type: slate
  lr_warmup_steps: 30000
  tau_anneal_steps: 30000
  vis_attn_type: sbd

token_vis:
  start_with_small_dataset: True
  start_num_episodes: 1000
  enable_dict_reset: False
  increase_dataset: True
  increase_after_steps: 0
  increase_per_steps: 10